// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://voyoujcftipbqcfhopcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZveW91amNmdGlwYnFjZmhvcGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0ODQzNTksImV4cCI6MjA3NTA2MDM1OX0.a3uvjRj9Q5onQVjYXFDGNCPSIJ-4-N2GB6mBIQ_FGNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);